#### Numpy

In [1]:
import numpy as np

In [3]:
#creamos arreglo de 1 dimension con 5 elementos
arr1 = np.array([1, 2, 3, 4, 5, 6])

print("Arreglo 1D: ", arr1)
print("Forma(shape): ", arr1.shape)
print("Tipos de datos (dtype): ", arr1.dtype)

Arreglo 1D:  [1 2 3 4 5 6]
Forma(shape):  (6,)
Tipos de datos (dtype):  int64


In [6]:
#cambiar la forma del arreglo a una matriz de 2x3
arr2 = arr1.reshape((2,3))

print("Arreglo 2D: \n", arr2)
print("Forma(shape): ", arr2.shape)
print("Tipos de datos (dtype): ", arr2.dtype)

Arreglo 2D: 
 [[1 2 3]
 [4 5 6]]
Forma(shape):  (2, 3)
Tipos de datos (dtype):  int64


In [7]:
#crear una matriz con forma (4,4) con numeros aleatorios entre 0 y 1
matrix = np.random.rand(4,4)



print("Arreglo 2D: \n", matrix)
print("Forma(shape): ", matrix.shape)
print("Tipos de datos (dtype): ", matrix.dtype)

Arreglo 2D: 
 [[0.1978203  0.13284023 0.61655184 0.02356105]
 [0.9489038  0.33427405 0.44905674 0.61834263]
 [0.39301695 0.39811458 0.29176666 0.88404535]
 [0.84046821 0.8102562  0.77624889 0.94163867]]
Forma(shape):  (4, 4)
Tipos de datos (dtype):  float64


In [10]:
#creaar un arreglo de 2 dimensiones a partir de una lista de listas
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr, type(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [11]:
#crear un arreglo de ceros con una forma (3, 4)
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
#crear un arreglo con unos con una forma (2,2)
arr = np.ones((2,2))
arr[1,1] = 10
print(arr)

[[ 1.  1.]
 [ 1. 10.]]


In [14]:
#Crear una matriz de identidad 
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# Crear un arreglo 3D de ceros con forma (2, 3, 4)
arr = np.zeros((2, 3, 4))
arr[0,1,2] = 5
arr

array([[[0., 0., 0., 0.],
        [0., 0., 5., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
#arreglo original
arr = np.random.rand(2, 5)
arr

array([[0.91093153, 0.16197967, 0.86514674, 0.93247512, 0.65820839],
       [0.93577176, 0.30696963, 0.39214244, 0.9979222 , 0.0810966 ]])

In [18]:
#arregloT (Transpuesta) 
arr.T

array([[0.91093153, 0.93577176],
       [0.16197967, 0.30696963],
       [0.86514674, 0.39214244],
       [0.93247512, 0.9979222 ],
       [0.65820839, 0.0810966 ]])

In [19]:
arr11 = np.array([[1,2], [3, 4]])
arr22 = np.array([[5,6],[7,8]])

arr11, arr22

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [20]:
#concatenar arreglos horisontalmente
array_h = np.hstack((arr11, arr22))
array_h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [21]:
#concatenar arreglos verticalmente
arr_v = np.vstack((arr11, arr22))
arr_v

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [22]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [24]:
#calcualr la suma de elementos
suma = np.sum(arr)
print(suma)

15


In [26]:
#calcualr el promedio de los elementos
promedio = np.mean(arr)
print(promedio)

3.0


In [27]:
#calcular la mediana
mediana = np.mean(arr)
print(mediana)

3.0


In [28]:
#calcualr el producto de los elementos
producto = np.prod(arr)
print(producto)

120


In [29]:
#obtenr la desviacion estandar
desvi_est = np.std(arr)
print(desvi_est)

1.4142135623730951


In [30]:
#calcualr la varianaz
var = np.var(arr)
print(var)

2.0


In [31]:
#minimo de los elementos
minimo = np.min(arr)
print(minimo)

1


In [32]:
#maximo de los elementos
maximo = np.max(arr)
print(maximo)

5


In [34]:
#calcular la suma acumulativa
cumsum = np.cumsum(arr)
print(cumsum)

[ 1  3  6 10 15]


In [35]:
#suma element-wise
arr + arr

array([ 2,  4,  6,  8, 10])

In [36]:
#restaa element-wise
arr - arr 

array([0, 0, 0, 0, 0])

In [37]:
#multiplicacion element-wise
arr * arr

array([ 1,  4,  9, 16, 25])

In [39]:
#division element-wise
arr // arr

array([1, 1, 1, 1, 1])